#!/bin/bash

function error {
  echo -e "\e[91m$1\e[39m"
  exit 1
}

cd "$HOME"

#ensure non-root
if [[ "$(id -u)" == 0 ]]; then
  error "L4T-Apps is not designed to be installed as root! Please try again as a regular user."
fi

#ensure debian
command -v apt >/dev/null || error "apt: command not found. Most likely this system is not running Debian."

#Ensure running arm processor
if uname -m | grep -q 'x86' ;then
  error "L4T-Apps is not not supported on non-arm processor architectures like amd64 and i386."
fi

sudo apt update || error "The command 'sudo apt update' failed. Before L4T-Apps will work, you must fix your apt package-management system."

#install dependencies
dependencies='yad curl wget aria2 lsb-release apt-utils imagemagick bc librsvg2-bin locales'
## Install dependencies if necessary
if ! dpkg -s $dependencies >/dev/null 2>&1; then
  sudo apt install $dependencies -y -f --no-install-recommends
fi

#remove annoying "YAD icon browser" launcher
sudo rm -f /usr/share/applications/yad-icon-browser.desktop

#download l4t-apps if folder missing
DIRECTORY="$(readlink -f "$(dirname "$0")")"
if [ -z "$DIRECTORY" ] || [ "$DIRECTORY" == "$HOME" ] || [ "$DIRECTORY" == bash ];then
  DIRECTORY="$HOME/l4t-apps"
  
  #if directory does not exist, download it
  if [ ! -d "$DIRECTORY" ];then
    echo "Downloading L4T-Apps..."
    output="$(git clone --depth 1 https:/git.dark98.co.uk/Dark98/l4t-apps "$DIRECTORY" 2>&1)"
    if [ ! -d "$DIRECTORY" ];then
      error "L4T-Apps download failed!\ngit clone output was: $output"
    fi
  fi
fi #Past this point, DIRECTORY variable populated with valid l4t-apps directory

#if chromeOS, install lxterminal
if command -v garcon-terminal-handler >/dev/null ;then
  echo "In order to install apps on chromeOS, a working terminal emulator is required.
Installing lxterminal in 10 seconds... (press Ctrl+C to cancel)"
  sleep 10
  sudo apt install -yf lxterminal || error "Failed to install lxterminal on chromeOS!"
fi

#menu button
if [ ! -f ~/.local/share/applications/l4t-apps.desktop ];then
  echo "Creating menu button..."
fi
mkdir -p ~/.local/share/applications
echo "[Desktop Entry]
Name=L4T-Apps
Comment=Raspberry Linux4Tegra App Store for open source projects
Exec=${DIRECTORY}/gui
Icon=${DIRECTORY}/icons/logo.png
Terminal=false
Type=Application
Categories=Utility;
StartupNotify=true" > ~/.local/share/applications/l4t-apps.desktop

if [ ! -f ~/.local/share/applications/l4t-apps-settings.desktop ];then
  echo "Creating Settings menu button..."
fi
echo "[Desktop Entry]
Name=L4T-Apps Settings
Comment=Configure L4T-Apps or create an App
Exec=${DIRECTORY}/settings
Icon=${DIRECTORY}/icons/settings.png
Terminal=false
Type=Application
Categories=Settings;
StartupNotify=true" > ~/.local/share/applications/l4t-apps-settings.desktop

if [ ! -f ~/.config/autostart/l4t-apps-updater.desktop ];then
  echo "Creating autostarted updater..."
fi
mkdir -p ~/.config/autostart
echo "[Desktop Entry]
Name=L4T-Apps Updater
Exec=${DIRECTORY}/updater onboot
Icon=${DIRECTORY}/icons/logo.png
Terminal=false
Type=Application
X-GNOME-Autostart-enabled=true
Hidden=false
NoDisplay=false" > ~/.config/autostart/l4t-apps-updater.desktop

mkdir -p "${DIRECTORY}/data" && cd "${DIRECTORY}/data" || error "Failed to make and enter ${DIRECTORY}/data directory!"
mkdir -p installed-packages preload settings status update-status categories
cd $HOME

#hide template app by default
"${DIRECTORY}/etc/categoryedit" "template" 'hidden' >/dev/null

#hide duplicates if running in twisteros
if [ -f /usr/local/bin/twistver ] && [[ $(twistver) == "Twister OS version"* ]]; then
  #twisteros full
  apps="CommanderPi
Box86
Discord
piKiss
Retropie
Scrcpy
Steam
Windows 10 Theme
Chromium Widevine
Lightpad
Wine (x86)
Mac OS Theme"
  PREIFS="$IFS"
  IFS=$'\n'
  for app in $apps ;do
    "${DIRECTORY}/etc/categoryedit" "$app" 'hidden' >/dev/null
  done
  IFS="$PREIFS"
  
elif [ -f /usr/local/bin/twistver ] && [[ $(twistver) != "Twister OS version"* ]]; then
  #twisteros lite
  PREIFS="$IFS"
  IFS=$'\n'
  apps="Chromium Widevine
Box86
Windows 10 Theme
Lightpad
Wine (x86)
Mac OS Theme"
  for app in $apps ;do
    "${DIRECTORY}/etc/categoryedit" "$app" 'hidden' >/dev/null
  done
  IFS="$PREIFS"
  
  #unhide some apps on twisteros lite that were hidden.
  #This removes certain apps completely from the category file. Effectively resets them to online default.
  "${DIRECTORY}/etc/categoryedit" CommanderPi --delete >/dev/null
  "${DIRECTORY}/etc/categoryedit" Discord --delete >/dev/null
  "${DIRECTORY}/etc/categoryedit" piKiss --delete >/dev/null
  "${DIRECTORY}/etc/categoryedit" Scrcpy --delete >/dev/null
  "${DIRECTORY}/etc/categoryedit" Steam --delete >/dev/null
  "${DIRECTORY}/etc/categoryedit" 'Chromium Widevine' --delete >/dev/null
  
  echo "Finished hiding apps on TwisterOS."
fi

#l4t-apps terminal command
if [ ! -f /usr/local/bin/l4t-apps ] || ! cat /usr/local/bin/l4t-apps | grep -q "${DIRECTORY}/gui";then
  echo "#!/bin/bash
${DIRECTORY}/gui"' "$@"' | sudo tee /usr/local/bin/l4t-apps >/dev/null
  sudo chmod +x /usr/local/bin/l4t-apps
  echo "You can now launch l4t-apps from a terminal, just by running 'l4t-apps'"
fi

#generate settings
if [ "$(ls "$DIRECTORY/data/settings" 2>/dev/null | wc -l)" -le 2 ];then
  echo "Generating default settings..."
fi
"${DIRECTORY}/settings" refresh

#preload app list
if [ ! -f "$DIRECTORY/data/preload/LIST-" ];then
  echo "Preloading app list..."
fi
"${DIRECTORY}/preload" &>/dev/null

#generate splash screen
if [ ! -f "${DIRECTORY}/icons/splashscreen.png" ];then
  echo "Generating loading screen..."
fi
"${DIRECTORY}/api" generate_splashscreen

echo "Installation complete."

